### ISSUE TITLE
Incompatible with SQL Alchemy 2.x

### ISSUE THREAD

**Issue by kand617** [SAP/sqlalchemy-hana#98] opened 2023-05-15 09:46 UTC
SQL Hana Dialect seems to not be compatible with SQL Alchemy 2.0.
Is there any plans to support newer versions?

**Comment by SirUli** [comment] 2023-07-05 14:57
Potential duplicate of #94. Unfortunately SAP so far didn't continue... :/

**Closed as completed** 2023-10-04 13:17 UTC
