### ISSUE TITLE
Column length not returned for NVARCHAR columns when inspecting a HANA Cloud view

### ISSUE THREAD

**Issue by JanFetzer** [SAP/sqlalchemy-hana#78] opened 2020-11-25 12:18 UTC
Hi, 
I am using sqlalchemy.engine.reflection.Inspector to relect view column of a database view in HANA Cloud. 
```

inspector = reflection.Inspector.from_engine(engine)
colTypes = inspector.get_columns(table_name="myView", schema="mySchema")
```

while the view actually has fields id & user of data type NVARCHAR with length =5000 and 255 respectively, what I get for colTypes is 
```
[{'name': 'id',
  'default': None,
  'nullable': True,
  'comment': None,
  'type': NVARCHAR()},
 {'name': 'user',
  'default': None,
  'nullable': True,
  'comment': None,
  'type': NVARCHAR()}]
```

The SQL generated is this (I inspected it with echo=True when creating the engine object):
```
SELECT COLUMN_NAME, DATA_TYPE_NAME, DEFAULT_VALUE, IS_NULLABLE, LENGTH, SCALE, COMMENTS FROM (
                   SELECT SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, POSITION, DATA_TYPE_NAME, DEFAULT_VALUE, IS_NULLABLE,
                   LENGTH, SCALE, COMMENTS FROM SYS.TABLE_COLUMNS UNION ALL SELECT SCHEMA_NAME, VIEW_NAME AS TABLE_NAME,
                   COLUMN_NAME, POSITION, DATA_TYPE_NAME, DEFAULT_VALUE, IS_NULLABLE, LENGTH, SCALE, COMMENTS FROM
                   SYS.VIEW_COLUMNS) AS COLUMS WHERE SCHEMA_NAME=? AND TABLE_NAME=? ORDER BY POSITION
```

and it correctly contains the column length (see screenshot), but the information gets lost while passing it on to SQLAlchemy. 
As a result, I cannot e.g. generate a table with same column type specification, since if I specify its column dtypes as NVARCHAR(), the default field length is 1, and my data will not fit

Actual view column types on DB
![Capture](https://user-images.githubusercontent.com/4488583/100226532-2ddf4d00-2f20-11eb-9713-29f800e90728.PNG)

Result of relevant part of above SQL: 
![Capture2](https://user-images.githubusercontent.com/4488583/100226939-ad6d1c00-2f20-11eb-93fe-725203803ebe.PNG)

**Comment by kasium** [comment] 2023-10-31 13:48
I cannot reproduce the issues anymore with the latest main. I guess it was fixed with 7ae694157af40c7f36a4af6aae4c0b517b46233a. Please wait until version 1.0 was released and then try again

**Closed by kasium** 2023-10-31 13:48 UTC
Labels: bug
