### ISSUE TITLE
Existing tables not recognized when autogenerating migrations with alembic

### ISSUE THREAD

**Issue by therhaag** [SAP/sqlalchemy-hana#148] opened 2023-11-09 12:15 UTC
Hi, I'm trying sqlalchemy-hana-1.0.0rc1 since I would like to use alembic to manage migrations in one of my projects. As I was playing with up/downgrades on the test system, I noticed the following behaviour:

After defining a few tables in my model, I autogenerated the first migration to create those in the DB. This worked fine and applying the migration resulted in the state shown in the first screenshot.

![Screenshot 2023-11-09 at 13 11 27](https://github.com/SAP/sqlalchemy-hana/assets/51459506/24aecbbc-073b-481b-943f-61e5d26ae535)

However, if I generate another migration (without any changes to my model), alembic still claims that all tables are new:
![Screenshot 2023-11-09 at 13 13 35](https://github.com/SAP/sqlalchemy-hana/assets/51459506/078d2e2f-e2b1-4b34-a94e-4d14e57f9009)

I have not experienced this behaviour with other DBs before, so I assume it's connected to the specific dialect, although I don't know for sure. It would be great if you could try to reproduce it.

**Comment by kasium** [comment] 2023-11-09 12:28
Thanks for reporting this issue. Let me have a look

**Comment by kasium** [comment] 2023-11-09 12:47
Okay, I checked I cannot reproduce the issue.  I have two hypothesises
* you don't use the default schema leading to issues
* you are using an older alembic version

Please share the following details
- python version
- sqlalchemy version
- alembic version
- HANA version and edition (cloud or onprem)
- A full reproducible example (incl. your env.py and the model)

Please be so kind a make it minimal.

**Comment by therhaag** [comment] 2023-11-09 13:00
Hi - thank you for looking into it. Indeed, I'm not using the default schema, but have set `include_schemas=True` in the run_migrations* functions. Perhaps I'm missing the schema information at another place I'm not aware of - will check. Versions should be recent:

python 3.9.16
sqlalchemy 2.0.20
alembic 1.12.1
HANA 2.00.059.08.1678802465 onprem

It will take a bit of time to generate a minimal example, I will come back to you.

**Comment by therhaag** [comment] 2023-11-09 13:23
Please find the stripped down model and my env.py attached. The alembic.ini has not been altered except for the connection string. Let me know if you need additional context.
[example.zip](https://github.com/SAP/sqlalchemy-hana/files/13308543/example.zip)

**Comment by kasium** [comment] 2023-11-09 14:01
Thanks for the example. Here are my findings.

Yes, it is related to this dialect but also to your code. Here is what you need to change

1. Use the lowercase schema name in the model: `__table_args__ = {"schema": "ANALYTICSTU"}` -> `__table_args__ = {"schema": "analyticstu"}`
2. Use the lowercase schema name in include_name: `return name in ["ANALYTICSTU"]` -> `return name in ["analyticstu"]`

You can find [here](https://github.com/SAP/sqlalchemy-hana#case-sensitivity) the explanation why this weird changes are needed. But in short: If SAP HANA shows you an uppercase name with no special characters, you need to use the lowercase name in SQLAlchemy/Alembic. And to directly answer this question: no, we cannot improve the behaviour.

Let me close this issue for now. Please let me know if the fixes work out

**Closed by kasium** 2023-11-09 14:01 UTC
Labels: bug, need-info

**Comment by therhaag** [comment] 2023-11-09 14:34
Thank you very much - this solved the issue after also changing table and column names to lowercase. Must have overlooked the paragraph in the README.
